"""One-time emergency recovery for the Supabase Free database-size limit.

Approved cleanup retains all Adaptive Router results, all promoted candidates,
all incubating/discovery/validated candidates, and the strongest deep-search
candidates. It never touches tokens, validation decisions, or paper trades.

Only run when the database is over quota AND currently read-only. The recovery
uses two PostgreSQL transactions and a session-local temporary staging table:
either the research candidates are restored completely or the truncate rolls
back. TRUNCATE physically reclaims space without requiring VACUUM FULL.
"""

from __future__ import annotations

import logging
from typing import Any

import psycopg

log = logging.getLogger("microtrader.storage")


async def reclaim_overquota_storage(database_url: str) -> dict[str, Any]:
    """Reclaim old, inactive research data while preserving active evidence.

    Raises on any failure. No change to the research score / promotion gates.
    """
    if not database_url:
        raise RuntimeError("Missing database URL")

    async with await psycopg.AsyncConnection.connect(
        database_url, connect_timeout=8, autocommit=True
    ) as conn:
        # Supabase explicitly documents this recovery override while a Free
        # project is quota-locked. Only this maintenance session is writable.
        await conn.execute("SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE")
        cur = await conn.execute(
            "SELECT pg_database_size(current_database()), "
            "current_setting('transaction_read_only')"
        )
        size_bytes, read_only = await cur.fetchone()
        size_mb = round(int(size_bytes) / 1048576, 1)
        if size_mb <= 475:
            return {"changed": False, "size_before_mb": size_mb}
        if read_only == "on":
            raise RuntimeError("Unable to enable a read-write maintenance session")

        log.warning("Storage emergency recovery: database %.1f MB", size_mb)

        # The old ForexLab is disabled by the active research pipeline.
        # Decision logs are written but never read back by ResearchAgent.
        # Both tables are regenerated by their stores when needed.
        async with conn.transaction():
            await conn.execute("SET LOCAL lock_timeout = '5s'")
            await conn.execute("SET LOCAL statement_timeout = '30s'")
            await conn.execute("TRUNCATE TABLE public.microtrader_forex_strategy_runs")
            await conn.execute("TRUNCATE TABLE public.microtrader_agent_decisions")

        # This COPY -> TRUNCATE -> RESTORE operation is atomic. The temporary
        # table only lives within this session and is never exposed in public.
        async with conn.transaction():
            await conn.execute("SET LOCAL lock_timeout = '8s'")
            await conn.execute("SET LOCAL statement_timeout = '180s'")
            await conn.execute(
                """
                CREATE TEMP TABLE microtrader_valuable_research
                ON COMMIT DROP AS
                SELECT r.*
                FROM public.microtrader_forex_research_strategy_results AS r
                WHERE r.promoted IS TRUE
                   OR r.strategy = 'adaptive_router'
                   OR r.funnel_stage IN ('incubator', 'discovery', 'validated')
                   OR r.signature IN (
                       SELECT d.signature
                       FROM public.microtrader_forex_research_strategy_results AS d
                       WHERE d.funnel_stage = 'deep_search'
                       ORDER BY d.funnel_score DESC NULLS LAST, d.tested_at DESC
                       LIMIT 400
                   )
                """
            )
            cur = await conn.execute(
                "SELECT COUNT(*) FROM microtrader_valuable_research"
            )
            kept_rows = int((await cur.fetchone())[0])
            if kept_rows < 100:
                raise RuntimeError(
                    f"Refusing to truncate research table: only {kept_rows} candidates staged"
                )
            cur = await conn.execute(
                "SELECT COUNT(*) FROM public.microtrader_forex_research_strategy_results"
            )
            original_rows = int((await cur.fetchone())[0])
            if kept_rows >= original_rows:
                raise RuntimeError("Nothing to reclaim in research table")

            await conn.execute(
                "TRUNCATE TABLE public.microtrader_forex_research_strategy_results"
            )
            await conn.execute(
                """
                INSERT INTO public.microtrader_forex_research_strategy_results
                SELECT * FROM microtrader_valuable_research
                """
            )
            cur = await conn.execute(
                "SELECT COUNT(*) FROM public.microtrader_forex_research_strategy_results"
            )
            saved_rows = int((await cur.fetchone())[0])
            if saved_rows != kept_rows:
                raise RuntimeError(
                    f"Research preservation check failed: {saved_rows} != {kept_rows}"
                )
        # PostgreSQL commits before the temporary archive is dropped.
        cur = await conn.execute(
            "SELECT pg_database_size(current_database())"
        )
        after_mb = round(int((await cur.fetchone())[0]) / 1048576, 1)
        log.warning(
            "Recovery complete: %s of %s research candidates retained, "
            "database %.1f -> %.1f MB",
            kept_rows, original_rows, size_mb, after_mb,
        )
        return {
            "changed": True, "size_before_mb": size_mb,
            "size_after_mb": after_mb,
            "research_rows_before": original_rows,
            "research_rows_retained": kept_rows,
        }
